name: Update flake.lock

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        run: nix flake update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "flake.lock: update"
          branch: flake-update
          title: "flake.lock: update"
          body: Automated flake.lock update.
